version: 2.1

orbs:
  node: circleci/node@4.1
  snyk: syk/snyk@0.0.13


jobs:
  unit-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

  security-check:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run audit
          command: npm audit
      - snyk/scan

workflows:
  test-deploy:
    jobs:
      - unit-test
      - security-check
