version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  unit-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

  npm-audit:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run audit
          command: npm audit

  security-check:
    docker:
      - image: aquasec/trivy
    steps:
      - checkout
      - run:
          name: Debug
          command: ls -all
      - run:
          name: Run security check
          command: trivy fs ./

workflows:
  test-deploy:
    jobs:
      - unit-test
      - npm-audit
      - security-check
